<?xml version="1.0"?>
<package format="2">
  <name>gello_ros</name>
  <version>0.0.0</version>
  <description>The gello_ros package</description>

  <maintainer email="yusaku_nakajima@ap.eng.osaka-u.ac.jp">Yusaku Nakajima</maintainer>

  <license>MIT</license>

  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>dynamixel_sdk</depend>
  <depend>realsense2_camera</depend>
  <depend>libuvc_camera</depend>
  <depend>cv_bridge</depend>
  <depend>spacenav_node</depend>

  <buildtool_depend>catkin</buildtool_depend>

  <export>

  </export>
</package>